program: generate_rnaseq_embeddings.py
method: bayes
project: rnaseq_vae
entity: tnnandi
metric:
  name: val_loss
  goal: minimize  
parameters:
  intermediate_dim:
    min: 256
    max: 512
  learning_rate:
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-2
#  beta:
#    min: 0.001
#    max: 0.01

